In [61]:
import numpy as np
import pandas as pd

In [62]:
df=pd.read_csv(r"C:\Users\l\Desktop\smaratdataset.csv")

In [63]:
df.head()
X=df.iloc[:95, 2:6].values
y=df.loc[:,'croptype'].values
print(X)
print(y)


[[ 60.   25.   80.    6. ]
 [ 50.    5.   70.    7. ]
 [ 70.   15.   75.    8.5]
 [ 60.   26.   60.    7. ]
 [ 70.   28.   75.    7. ]
 [ 50.   12.   65.    6. ]
 [ 55.    7.   78.    6. ]
 [ 70.    0.   68.    6.5]
 [ 60.   15.   75.    7.2]
 [ 50.    7.   60.    5.5]
 [ 50.   27.   50.    6. ]
 [ 60.   12.   45.    9. ]
 [ 65.   20.   55.    7.6]
 [ 40.   24.   45.    6. ]
 [ 55.   10.   60.    7. ]
 [ 50.   21.   65.    5.5]
 [ 55.   30.   50.    7. ]
 [ 60.   25.   65.    6. ]
 [ 70.   17.   75.    7. ]
 [ 75.   15.   60.    6. ]
 [ 75.  -13.   50.    5. ]
 [ 60.   28.   60.    7. ]
 [ 75.   20.   50.    8. ]
 [ 70.   18.   65.    6. ]
 [ 50.   12.   45.    4. ]
 [ 80.   30.   65.    6. ]
 [ 70.   47.   55.    5. ]
 [ 50.   10.   60.    5.5]
 [ 75.    8.   15.    5. ]
 [ 65.    3.   70.    5. ]
 [ 55.   10.   35.    6. ]
 [ 50.   24.   60.    6.5]
 [ 60.   23.   70.    6.5]
 [ 50.   15.    8.    7. ]
 [ 70.   40.   70.    5.5]
 [ 80.   10.   65.    5. ]
 [ 70.   15.   80.    4.5]
 

In [64]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
print(X)


[[ 7.42209812e-02  6.00636857e-01  2.78855536e-01 -1.70078872e-01]
 [-5.97302182e-01 -1.30901848e+00  8.21868210e-02  4.00857271e-01]
 [ 7.45744144e-01 -3.54190811e-01  1.80521179e-01  1.25726149e+00]
 [ 7.42209812e-02  6.96119624e-01 -1.14481894e-01  4.00857271e-01]
 [ 7.45744144e-01  8.87085157e-01  1.80521179e-01  4.00857271e-01]
 [-5.97302182e-01 -6.40639111e-01 -1.61475366e-02 -1.70078872e-01]
 [-2.61540600e-01 -1.11805294e+00  2.39521793e-01 -1.70078872e-01]
 [ 7.45744144e-01 -1.78643231e+00  4.28530780e-02  1.15389200e-01]
 [ 7.42209812e-02 -3.54190811e-01  1.80521179e-01  5.15044500e-01]
 [-5.97302182e-01 -1.11805294e+00 -1.14481894e-01 -4.55546944e-01]
 [-5.97302182e-01  7.91602391e-01 -3.11150610e-01 -1.70078872e-01]
 [ 7.42209812e-02 -6.40639111e-01 -4.09484967e-01  1.54272956e+00]
 [ 4.09982563e-01  1.23223023e-01 -2.12816252e-01  7.43418957e-01]
 [-1.26882534e+00  5.05154090e-01 -4.09484967e-01 -1.70078872e-01]
 [-2.61540600e-01 -8.31604645e-01 -1.14481894e-01  4.00857271e

In [65]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [66]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)
print(X_test)

[[-0.59730218  0.02774026 -0.31115061 -0.45554694]
 [ 0.74574414 -1.78643231  0.04285308  0.1153892 ]
 [ 1.41726731 -0.83160464  0.08218682 -0.17007887]
 [ 0.07422098 -0.06774251  0.18052118  0.1153892 ]
 [ 0.07422098 -0.06774251  0.27885554 -0.05589164]
 [ 0.07422098  0.12322302 -0.01614754 -0.45554694]
 [ 1.08150573 -1.02257018 -0.99949111 -0.74101502]
 [-0.59730218  0.79160239 -0.31115061 -0.17007887]
 [-0.59730218  1.65094729  8.53894158 -0.45554694]
 [ 0.07422098  0.21870579  0.18052118 -0.45554694]
 [ 0.74574414 -0.06774251 -0.01614754 -0.17007887]
 [ 0.07422098 -0.64063911 -0.40948497  1.54272956]
 [ 0.07422098  0.40967132  0.08218682  0.1153892 ]
 [ 1.08150573  0.88708516 -0.5274862  -0.17007887]
 [ 0.07422098  0.79160239  0.27885554  0.22957643]
 [-3.28339483 -1.02257018 -0.11448189 -0.17007887]
 [ 0.07422098  0.21870579 -0.21281625  0.40085727]
 [-1.26882534  1.55546452 -0.31115061  0.97179341]
 [-0.59730218  0.50515409 -0.11448189 -0.17007887]]


In [67]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X)
X=scaler.transform(X)
X_test=scaler.transform(X_test)

In [68]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [69]:

y_pred=classifier.predict(X_test)


In [70]:
print(X_test)
print(y_pred)


[[0.58333333 0.58208955 0.08536585 0.08823529]
 [0.86111111 0.29850746 0.12195122 0.14705882]
 [1.         0.44776119 0.12601626 0.11764706]
 [0.72222222 0.56716418 0.13617886 0.14705882]
 [0.72222222 0.56716418 0.14634146 0.12941176]
 [0.72222222 0.59701493 0.11585366 0.08823529]
 [0.93055556 0.41791045 0.01422764 0.05882353]
 [0.58333333 0.70149254 0.08536585 0.11764706]
 [0.58333333 0.8358209  1.         0.08823529]
 [0.72222222 0.6119403  0.13617886 0.08823529]
 [0.86111111 0.56716418 0.11585366 0.11764706]
 [0.72222222 0.47761194 0.07520325 0.29411765]
 [0.72222222 0.64179104 0.12601626 0.14705882]
 [0.93055556 0.71641791 0.06300813 0.11764706]
 [0.72222222 0.70149254 0.14634146 0.15882353]
 [0.02777778 0.41791045 0.10569106 0.11764706]
 [0.72222222 0.6119403  0.09552846 0.17647059]
 [0.44444444 0.82089552 0.08536585 0.23529412]
 [0.58333333 0.65671642 0.10569106 0.11764706]]
['mustard' 'chilli' 'coconut' 'wheat' 'wheat' 'wheat' 'coconut' 'mustard'
 'mustard' 'ginger' 'rice' 'garl

In [71]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.6842105263157895


In [60]:
xpre=[[25,7,60,9]]
ypre=classifier.predict(xpre)
print(ypre)

['coconut']
